Repository LuckyBicky-Team/Outsourcing-project, pull requests merged in 2024-06, with the labels that each got.

#4 feat: 헤더 및 레이아웃 적용
  index.html
  src/components/Layout/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/index.js
  src/pages/Home/Home.jsx
  src/routes/Router.jsx
  src/styles/GlobalStyle.js
Labels: enhancement

#6 fix: 맵 호환성 오류 수정 및 맵 최종
  index.html
  package.json
  src/App.jsx
  src/components/Layout/Header.jsx
  src/components/MapContainer.jsx
  src/main.jsx
  src/pages/MapPage/MapPage.jsx
  src/pages/MapPage/index.js
  src/pages/index.js
  src/routes/Router.jsx
  yarn.lock
Labels: enhancement

#8 feat: 시스템 컴포넌트 추가 - button, input, textarea
  index.html
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/Textarea.jsx
  src/styles/GlobalStyle.js
  src/styles/utils.js
Labels: enhancement

#12 feat: 피드백 cud 구현
  src/components/Board/Board.jsx
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/Layout/Header.jsx
  src/pages/Feedback/FeedbackDetail.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Feedback/PasswordCheck.jsx
  src/pages/Feedback/index.js
  src/pages/index.js
  src/routes/Router.jsx
  src/stores/queries/useFeedbackQueries.js
  src/supabase/feedback.js
Labels: enhancement

#13 feat: Home 컴포넌트 개선 및 데이터 로딩 추가
  jsconfig.json
  public/images/main-feature-bg.png
  public/images/main-space-1.png
  public/images/main-space-2.png
  public/images/main-space-3.png
  src/pages/Home/Home.jsx
Labels: enhancement

#16 feat: 메뉴 리스트 호버시 애니메이션 적용
  package.json
  src/apis/axios.js
  src/components/Board/Board.jsx
  src/components/Menu/MenuCategory.jsx
  src/components/Menu/MenuItem.jsx
  src/pages/Menu/Menu.jsx
  src/stores/zustand/index.js
Labels: enhancement

#18 fix: 게시판 crud 오류 수정
  src/components/Board/Board.jsx
  src/pages/Feedback/FeedbackDetail.jsx
  src/pages/Feedback/FeedbackError.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Feedback/PasswordCheck.jsx
  src/stores/queries/useFeedbackQueries.js
  src/supabase/supabaseFeedback.js
Labels: bug

#22 feat: query key constants 추가 및 components 컴포넌트 폴더화
  src/assets/react.svg
  src/components/Board/Board.jsx
  src/components/Button/Button.jsx
  src/components/Button/index.js
  src/components/Form/Input.jsx
  src/components/Form/Textarea.jsx
  src/components/Form/index.js
  src/components/index.js
  src/pages/Feedback/FeedbackDetail.jsx
  src/pages/Feedback/FeedbackError.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Feedback/PasswordCheck.jsx
  src/pages/Home/Home.jsx
  src/stores/queries/constants.js
  src/stores/queries/useFeedbackQueries.js
  src/stores/queries/useMenuQueries.js
Labels: enhancement

#27 style: 타이포 그라피 누락 부분 추가
  src/components/Board/Board.jsx
  src/pages/Feedback/FeedbackDetail.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Feedback/PasswordCheck.jsx
Labels: bug

#29 feat: map 컴포넌트 loader 적용
  src/components/Loader/Loader.jsx
  src/components/Loader/index.js
  src/components/Store/StoreContainer.jsx
Labels: enhancement

#28 feat: 리스트 infinite scroll 구현
  package.json
  src/components/Board/Board.jsx
  src/components/InfiniteScroll/InfiniteScroll.jsx
  src/components/InfiniteScroll/index.js
  src/components/Layout/Layout.jsx
  src/components/Menu/MenuList.jsx
  src/pages/Menu/Menu.jsx
  src/stores/queries/useFeedbackQueries.js
  src/stores/queries/useMenuQueries.js
  src/supabase/feedback.js
  src/supabase/menu.js
  yarn.lock
Labels: enhancement

#31 style: 반응형 스타일 수정 및 인터렉션 적용
  src/components/Board/Board.jsx
  src/components/Menu/MenuItem.jsx
  src/components/Menu/MenuList.jsx
  src/components/Store/StoreContainer.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Home/Home.jsx
Labels: enhancement

#32 fix: infinite scroll 되지 않는 오류 수정
  package.json
  src/components/InfiniteScroll/InfiniteScroll.jsx
  src/components/Menu/MenuItem.jsx
  src/pages/Home/Home.jsx
  src/stores/queries/constants.js
  src/stores/queries/useMenuQueries.js
  vite.config.js
  yarn.lock
Labels: bug

#34 Update README.md
  README.md
Labels: documentation

#35 chore: 1.0.1
  README.md
Labels: documentation

#36 fix: 지도 키 변경
  index.html
Labels: bug

#37 chore: 1.0.2
  index.html
Labels: bug

#38 refactor: 피드백을 바탕으로 최종 리팩터링
  src/api/feedback.js
  src/api/menu.js
  src/api/request.js
  src/api/supabaseClient.js
  src/components/Board/Board.jsx
  src/components/Layout/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Menu/MenuCategory.jsx
  src/components/Menu/MenuItem.jsx
  src/components/Menu/MenuList.jsx
  src/components/Store/StoreContainer.jsx
  src/pages/Feedback/FeedbackDetail.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Feedback/PasswordCheck.jsx
  src/pages/Home/Home.jsx
  src/pages/Menu/Menu.jsx
  src/stores/queries/useFeedbackQueries.js
  src/stores/queries/useMenuQueries.js
  src/styles/colorUtils.js
  src/styles/mediaQueries.js
  src/styles/styleUtils.js
  src/styles/theme.js
  src/styles/utils.js
  src/supabase/feedback.js
Labels: enhancement

#39 chore: 1.0.3
  src/api/feedback.js
  src/api/menu.js
  src/api/request.js
  src/api/supabaseClient.js
  src/components/Board/Board.jsx
  src/components/Layout/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Menu/MenuCategory.jsx
  src/components/Menu/MenuItem.jsx
  src/components/Menu/MenuList.jsx
  src/components/Store/StoreContainer.jsx
  src/pages/Feedback/FeedbackDetail.jsx
  src/pages/Feedback/FeedbackForm.jsx
  src/pages/Feedback/PasswordCheck.jsx
  src/pages/Home/Home.jsx
  src/pages/Menu/Menu.jsx
  src/stores/queries/useFeedbackQueries.js
  src/stores/queries/useMenuQueries.js
  src/styles/colorUtils.js
  src/styles/mediaQueries.js
  src/styles/styleUtils.js
  src/styles/theme.js
  src/styles/utils.js
  src/supabase/feedback.js
Labels: enhancement
